# models/square.py
from models.rectangle import Rectangle

class Square(Rectangle):
    def __init__(self, size, x=0, y=0, id=None):
        """
        Constructor for the Square class.

        Parameters:
        - size (int): The size of the square.
        - x (int, optional): The x-coordinate of the square's position. Defaults to 0.
        - y (int, optional): The y-coordinate of the square's position. Defaults to 0.
        - id (int, optional): The identifier of the square. If None, it will be generated by the Base class.

        Attributes (inherited from Rectangle):
        - __width (int): Width of the square.
        - __height (int): Height of the square.
        - __x (int): x-coordinate of the square's position.
        - __y (int): y-coordinate of the square's position.
        """
        super().__init__(size, size, x, y, id)  # Call the super class with id, x, y, width, and height

    def __str__(self):
        """
        Overloaded __str__ method to represent the Square object as a string.

        Returns:
        - str: A string representation of the Square object.
        """
        return f"[Square] ({self.id}) {self.x}/{self.y} - {self.width}"

# Example usage:
square = Square(5, 2, 1, 42)
print(square)  # Output: [Square] (42) 2/1 - 5
